services:
  api:
    build: .
    container_name: idiomas-api
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 5076:5076

  database:
    build: ./database
    container_name: idiomas-database
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s


  migration:
    build:
      context: .
      target: build
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["dotnet", "ef", "database", "update"]
    env_file:
      - .env
    
volumes:
  mssql_data: