services:
  api:
    build: ./Idiomas.Core
    container_name: idiomas-api
    depends_on:
      database:
        condition: service_healthy
      mailpit:
        condition: service_started
    env_file:
      - .env
    ports:
      - 5076:5076
    networks:
      - idiomas-network

  database:
    build: ./Idiomas.Core/Infrastructure/Database/Docker
    container_name: idiomas-database
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - idiomas-network

  migration:
    build:
      context: ./Idiomas.Core
      dockerfile: Infrastructure/Database/Docker/Dockerfile.migration
    container_name: idiomas-migration
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./Idiomas.Core:/source
    networks:
      - idiomas-network

  test:
    build:
      context: .
      dockerfile: ./Idiomas.Tests.Core/Dockerfile.test
    container_name: idiomas-test
    env_file:
      - .env
    networks:
      - idiomas-network

  mailpit:
    image: axllent/mailpit:v1.22
    container_name: idiomas-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - idiomas-network

volumes:
  mssql_data:

networks:
  idiomas-network:
    driver: bridge