# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /source

RUN dotnet tool install --global dotnet-ef --version 9.0.11
ENV PATH="$PATH:/root/.dotnet/tools"

COPY ./Infrastructure/Database/Docker/migration-entrypoint.sh /usr/local/bin/migration-entrypoint.sh
RUN chmod +x /usr/local/bin/migration-entrypoint.sh

ENTRYPOINT ["migration-entrypoint.sh"]
CMD ["migrate"]
