# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /source

COPY Idiomas.sln ./
COPY Idiomas.Core/Idiomas.Core.csproj ./Idiomas.Core/
COPY Idiomas.Tests.Core/Idiomas.Tests.Core.csproj ./Idiomas.Tests.Core/

RUN dotnet restore Idiomas.sln

COPY . .

ENTRYPOINT ["dotnet", "test"]
